package com.song.trip.web.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FoodExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_food
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_food
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_food
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_food
     *
     * @mbg.generated
     */
    public FoodExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_food
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_food
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_food
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_food
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_food
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_food
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_food
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_food
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_food
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_food
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tp_food
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTpFidIsNull() {
            addCriterion("tp_fid is null");
            return (Criteria) this;
        }

        public Criteria andTpFidIsNotNull() {
            addCriterion("tp_fid is not null");
            return (Criteria) this;
        }

        public Criteria andTpFidEqualTo(Integer value) {
            addCriterion("tp_fid =", value, "tpFid");
            return (Criteria) this;
        }

        public Criteria andTpFidNotEqualTo(Integer value) {
            addCriterion("tp_fid <>", value, "tpFid");
            return (Criteria) this;
        }

        public Criteria andTpFidGreaterThan(Integer value) {
            addCriterion("tp_fid >", value, "tpFid");
            return (Criteria) this;
        }

        public Criteria andTpFidGreaterThanOrEqualTo(Integer value) {
            addCriterion("tp_fid >=", value, "tpFid");
            return (Criteria) this;
        }

        public Criteria andTpFidLessThan(Integer value) {
            addCriterion("tp_fid <", value, "tpFid");
            return (Criteria) this;
        }

        public Criteria andTpFidLessThanOrEqualTo(Integer value) {
            addCriterion("tp_fid <=", value, "tpFid");
            return (Criteria) this;
        }

        public Criteria andTpFidIn(List<Integer> values) {
            addCriterion("tp_fid in", values, "tpFid");
            return (Criteria) this;
        }

        public Criteria andTpFidNotIn(List<Integer> values) {
            addCriterion("tp_fid not in", values, "tpFid");
            return (Criteria) this;
        }

        public Criteria andTpFidBetween(Integer value1, Integer value2) {
            addCriterion("tp_fid between", value1, value2, "tpFid");
            return (Criteria) this;
        }

        public Criteria andTpFidNotBetween(Integer value1, Integer value2) {
            addCriterion("tp_fid not between", value1, value2, "tpFid");
            return (Criteria) this;
        }

        public Criteria andTpFtitleIsNull() {
            addCriterion("tp_ftitle is null");
            return (Criteria) this;
        }

        public Criteria andTpFtitleIsNotNull() {
            addCriterion("tp_ftitle is not null");
            return (Criteria) this;
        }

        public Criteria andTpFtitleEqualTo(String value) {
            addCriterion("tp_ftitle =", value, "tpFtitle");
            return (Criteria) this;
        }

        public Criteria andTpFtitleNotEqualTo(String value) {
            addCriterion("tp_ftitle <>", value, "tpFtitle");
            return (Criteria) this;
        }

        public Criteria andTpFtitleGreaterThan(String value) {
            addCriterion("tp_ftitle >", value, "tpFtitle");
            return (Criteria) this;
        }

        public Criteria andTpFtitleGreaterThanOrEqualTo(String value) {
            addCriterion("tp_ftitle >=", value, "tpFtitle");
            return (Criteria) this;
        }

        public Criteria andTpFtitleLessThan(String value) {
            addCriterion("tp_ftitle <", value, "tpFtitle");
            return (Criteria) this;
        }

        public Criteria andTpFtitleLessThanOrEqualTo(String value) {
            addCriterion("tp_ftitle <=", value, "tpFtitle");
            return (Criteria) this;
        }

        public Criteria andTpFtitleLike(String value) {
            addCriterion("tp_ftitle like", value, "tpFtitle");
            return (Criteria) this;
        }

        public Criteria andTpFtitleNotLike(String value) {
            addCriterion("tp_ftitle not like", value, "tpFtitle");
            return (Criteria) this;
        }

        public Criteria andTpFtitleIn(List<String> values) {
            addCriterion("tp_ftitle in", values, "tpFtitle");
            return (Criteria) this;
        }

        public Criteria andTpFtitleNotIn(List<String> values) {
            addCriterion("tp_ftitle not in", values, "tpFtitle");
            return (Criteria) this;
        }

        public Criteria andTpFtitleBetween(String value1, String value2) {
            addCriterion("tp_ftitle between", value1, value2, "tpFtitle");
            return (Criteria) this;
        }

        public Criteria andTpFtitleNotBetween(String value1, String value2) {
            addCriterion("tp_ftitle not between", value1, value2, "tpFtitle");
            return (Criteria) this;
        }

        public Criteria andTpFnameIsNull() {
            addCriterion("tp_fname is null");
            return (Criteria) this;
        }

        public Criteria andTpFnameIsNotNull() {
            addCriterion("tp_fname is not null");
            return (Criteria) this;
        }

        public Criteria andTpFnameEqualTo(String value) {
            addCriterion("tp_fname =", value, "tpFname");
            return (Criteria) this;
        }

        public Criteria andTpFnameNotEqualTo(String value) {
            addCriterion("tp_fname <>", value, "tpFname");
            return (Criteria) this;
        }

        public Criteria andTpFnameGreaterThan(String value) {
            addCriterion("tp_fname >", value, "tpFname");
            return (Criteria) this;
        }

        public Criteria andTpFnameGreaterThanOrEqualTo(String value) {
            addCriterion("tp_fname >=", value, "tpFname");
            return (Criteria) this;
        }

        public Criteria andTpFnameLessThan(String value) {
            addCriterion("tp_fname <", value, "tpFname");
            return (Criteria) this;
        }

        public Criteria andTpFnameLessThanOrEqualTo(String value) {
            addCriterion("tp_fname <=", value, "tpFname");
            return (Criteria) this;
        }

        public Criteria andTpFnameLike(String value) {
            addCriterion("tp_fname like", value, "tpFname");
            return (Criteria) this;
        }

        public Criteria andTpFnameNotLike(String value) {
            addCriterion("tp_fname not like", value, "tpFname");
            return (Criteria) this;
        }

        public Criteria andTpFnameIn(List<String> values) {
            addCriterion("tp_fname in", values, "tpFname");
            return (Criteria) this;
        }

        public Criteria andTpFnameNotIn(List<String> values) {
            addCriterion("tp_fname not in", values, "tpFname");
            return (Criteria) this;
        }

        public Criteria andTpFnameBetween(String value1, String value2) {
            addCriterion("tp_fname between", value1, value2, "tpFname");
            return (Criteria) this;
        }

        public Criteria andTpFnameNotBetween(String value1, String value2) {
            addCriterion("tp_fname not between", value1, value2, "tpFname");
            return (Criteria) this;
        }

        public Criteria andTpAddressIsNull() {
            addCriterion("tp_address is null");
            return (Criteria) this;
        }

        public Criteria andTpAddressIsNotNull() {
            addCriterion("tp_address is not null");
            return (Criteria) this;
        }

        public Criteria andTpAddressEqualTo(String value) {
            addCriterion("tp_address =", value, "tpAddress");
            return (Criteria) this;
        }

        public Criteria andTpAddressNotEqualTo(String value) {
            addCriterion("tp_address <>", value, "tpAddress");
            return (Criteria) this;
        }

        public Criteria andTpAddressGreaterThan(String value) {
            addCriterion("tp_address >", value, "tpAddress");
            return (Criteria) this;
        }

        public Criteria andTpAddressGreaterThanOrEqualTo(String value) {
            addCriterion("tp_address >=", value, "tpAddress");
            return (Criteria) this;
        }

        public Criteria andTpAddressLessThan(String value) {
            addCriterion("tp_address <", value, "tpAddress");
            return (Criteria) this;
        }

        public Criteria andTpAddressLessThanOrEqualTo(String value) {
            addCriterion("tp_address <=", value, "tpAddress");
            return (Criteria) this;
        }

        public Criteria andTpAddressLike(String value) {
            addCriterion("tp_address like", value, "tpAddress");
            return (Criteria) this;
        }

        public Criteria andTpAddressNotLike(String value) {
            addCriterion("tp_address not like", value, "tpAddress");
            return (Criteria) this;
        }

        public Criteria andTpAddressIn(List<String> values) {
            addCriterion("tp_address in", values, "tpAddress");
            return (Criteria) this;
        }

        public Criteria andTpAddressNotIn(List<String> values) {
            addCriterion("tp_address not in", values, "tpAddress");
            return (Criteria) this;
        }

        public Criteria andTpAddressBetween(String value1, String value2) {
            addCriterion("tp_address between", value1, value2, "tpAddress");
            return (Criteria) this;
        }

        public Criteria andTpAddressNotBetween(String value1, String value2) {
            addCriterion("tp_address not between", value1, value2, "tpAddress");
            return (Criteria) this;
        }

        public Criteria andTpFpicIsNull() {
            addCriterion("tp_fpic is null");
            return (Criteria) this;
        }

        public Criteria andTpFpicIsNotNull() {
            addCriterion("tp_fpic is not null");
            return (Criteria) this;
        }

        public Criteria andTpFpicEqualTo(String value) {
            addCriterion("tp_fpic =", value, "tpFpic");
            return (Criteria) this;
        }

        public Criteria andTpFpicNotEqualTo(String value) {
            addCriterion("tp_fpic <>", value, "tpFpic");
            return (Criteria) this;
        }

        public Criteria andTpFpicGreaterThan(String value) {
            addCriterion("tp_fpic >", value, "tpFpic");
            return (Criteria) this;
        }

        public Criteria andTpFpicGreaterThanOrEqualTo(String value) {
            addCriterion("tp_fpic >=", value, "tpFpic");
            return (Criteria) this;
        }

        public Criteria andTpFpicLessThan(String value) {
            addCriterion("tp_fpic <", value, "tpFpic");
            return (Criteria) this;
        }

        public Criteria andTpFpicLessThanOrEqualTo(String value) {
            addCriterion("tp_fpic <=", value, "tpFpic");
            return (Criteria) this;
        }

        public Criteria andTpFpicLike(String value) {
            addCriterion("tp_fpic like", value, "tpFpic");
            return (Criteria) this;
        }

        public Criteria andTpFpicNotLike(String value) {
            addCriterion("tp_fpic not like", value, "tpFpic");
            return (Criteria) this;
        }

        public Criteria andTpFpicIn(List<String> values) {
            addCriterion("tp_fpic in", values, "tpFpic");
            return (Criteria) this;
        }

        public Criteria andTpFpicNotIn(List<String> values) {
            addCriterion("tp_fpic not in", values, "tpFpic");
            return (Criteria) this;
        }

        public Criteria andTpFpicBetween(String value1, String value2) {
            addCriterion("tp_fpic between", value1, value2, "tpFpic");
            return (Criteria) this;
        }

        public Criteria andTpFpicNotBetween(String value1, String value2) {
            addCriterion("tp_fpic not between", value1, value2, "tpFpic");
            return (Criteria) this;
        }

        public Criteria andTpFpriceIsNull() {
            addCriterion("tp_fprice is null");
            return (Criteria) this;
        }

        public Criteria andTpFpriceIsNotNull() {
            addCriterion("tp_fprice is not null");
            return (Criteria) this;
        }

        public Criteria andTpFpriceEqualTo(Integer value) {
            addCriterion("tp_fprice =", value, "tpFprice");
            return (Criteria) this;
        }

        public Criteria andTpFpriceNotEqualTo(Integer value) {
            addCriterion("tp_fprice <>", value, "tpFprice");
            return (Criteria) this;
        }

        public Criteria andTpFpriceGreaterThan(Integer value) {
            addCriterion("tp_fprice >", value, "tpFprice");
            return (Criteria) this;
        }

        public Criteria andTpFpriceGreaterThanOrEqualTo(Integer value) {
            addCriterion("tp_fprice >=", value, "tpFprice");
            return (Criteria) this;
        }

        public Criteria andTpFpriceLessThan(Integer value) {
            addCriterion("tp_fprice <", value, "tpFprice");
            return (Criteria) this;
        }

        public Criteria andTpFpriceLessThanOrEqualTo(Integer value) {
            addCriterion("tp_fprice <=", value, "tpFprice");
            return (Criteria) this;
        }

        public Criteria andTpFpriceIn(List<Integer> values) {
            addCriterion("tp_fprice in", values, "tpFprice");
            return (Criteria) this;
        }

        public Criteria andTpFpriceNotIn(List<Integer> values) {
            addCriterion("tp_fprice not in", values, "tpFprice");
            return (Criteria) this;
        }

        public Criteria andTpFpriceBetween(Integer value1, Integer value2) {
            addCriterion("tp_fprice between", value1, value2, "tpFprice");
            return (Criteria) this;
        }

        public Criteria andTpFpriceNotBetween(Integer value1, Integer value2) {
            addCriterion("tp_fprice not between", value1, value2, "tpFprice");
            return (Criteria) this;
        }

        public Criteria andTpPhoneIsNull() {
            addCriterion("tp_phone is null");
            return (Criteria) this;
        }

        public Criteria andTpPhoneIsNotNull() {
            addCriterion("tp_phone is not null");
            return (Criteria) this;
        }

        public Criteria andTpPhoneEqualTo(String value) {
            addCriterion("tp_phone =", value, "tpPhone");
            return (Criteria) this;
        }

        public Criteria andTpPhoneNotEqualTo(String value) {
            addCriterion("tp_phone <>", value, "tpPhone");
            return (Criteria) this;
        }

        public Criteria andTpPhoneGreaterThan(String value) {
            addCriterion("tp_phone >", value, "tpPhone");
            return (Criteria) this;
        }

        public Criteria andTpPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("tp_phone >=", value, "tpPhone");
            return (Criteria) this;
        }

        public Criteria andTpPhoneLessThan(String value) {
            addCriterion("tp_phone <", value, "tpPhone");
            return (Criteria) this;
        }

        public Criteria andTpPhoneLessThanOrEqualTo(String value) {
            addCriterion("tp_phone <=", value, "tpPhone");
            return (Criteria) this;
        }

        public Criteria andTpPhoneLike(String value) {
            addCriterion("tp_phone like", value, "tpPhone");
            return (Criteria) this;
        }

        public Criteria andTpPhoneNotLike(String value) {
            addCriterion("tp_phone not like", value, "tpPhone");
            return (Criteria) this;
        }

        public Criteria andTpPhoneIn(List<String> values) {
            addCriterion("tp_phone in", values, "tpPhone");
            return (Criteria) this;
        }

        public Criteria andTpPhoneNotIn(List<String> values) {
            addCriterion("tp_phone not in", values, "tpPhone");
            return (Criteria) this;
        }

        public Criteria andTpPhoneBetween(String value1, String value2) {
            addCriterion("tp_phone between", value1, value2, "tpPhone");
            return (Criteria) this;
        }

        public Criteria andTpPhoneNotBetween(String value1, String value2) {
            addCriterion("tp_phone not between", value1, value2, "tpPhone");
            return (Criteria) this;
        }

        public Criteria andTpFcreatedIsNull() {
            addCriterion("tp_fcreated is null");
            return (Criteria) this;
        }

        public Criteria andTpFcreatedIsNotNull() {
            addCriterion("tp_fcreated is not null");
            return (Criteria) this;
        }

        public Criteria andTpFcreatedEqualTo(Date value) {
            addCriterion("tp_fcreated =", value, "tpFcreated");
            return (Criteria) this;
        }

        public Criteria andTpFcreatedNotEqualTo(Date value) {
            addCriterion("tp_fcreated <>", value, "tpFcreated");
            return (Criteria) this;
        }

        public Criteria andTpFcreatedGreaterThan(Date value) {
            addCriterion("tp_fcreated >", value, "tpFcreated");
            return (Criteria) this;
        }

        public Criteria andTpFcreatedGreaterThanOrEqualTo(Date value) {
            addCriterion("tp_fcreated >=", value, "tpFcreated");
            return (Criteria) this;
        }

        public Criteria andTpFcreatedLessThan(Date value) {
            addCriterion("tp_fcreated <", value, "tpFcreated");
            return (Criteria) this;
        }

        public Criteria andTpFcreatedLessThanOrEqualTo(Date value) {
            addCriterion("tp_fcreated <=", value, "tpFcreated");
            return (Criteria) this;
        }

        public Criteria andTpFcreatedIn(List<Date> values) {
            addCriterion("tp_fcreated in", values, "tpFcreated");
            return (Criteria) this;
        }

        public Criteria andTpFcreatedNotIn(List<Date> values) {
            addCriterion("tp_fcreated not in", values, "tpFcreated");
            return (Criteria) this;
        }

        public Criteria andTpFcreatedBetween(Date value1, Date value2) {
            addCriterion("tp_fcreated between", value1, value2, "tpFcreated");
            return (Criteria) this;
        }

        public Criteria andTpFcreatedNotBetween(Date value1, Date value2) {
            addCriterion("tp_fcreated not between", value1, value2, "tpFcreated");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tp_food
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tp_food
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}