package com.song.trip.web.dao;

import com.song.trip.web.domain.Hotel;
import com.song.trip.web.domain.HotelExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface HotelDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_hotel
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer hid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_hotel
     *
     * @mbg.generated
     */
    int insert(Hotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_hotel
     *
     * @mbg.generated
     */
    int insertSelective(Hotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_hotel
     *
     * @mbg.generated
     */
    List<Hotel> selectByExampleWithBLOBs(HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_hotel
     *
     * @mbg.generated
     */
    List<Hotel> selectByExample(HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_hotel
     *
     * @mbg.generated
     */
    Hotel selectByPrimaryKey(Integer hid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_hotel
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Hotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_hotel
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Hotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_hotel
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Hotel record);
    /**
     * 酒店模糊查询
     * **/
    List<Hotel> hotelPointSearch(Hotel hotel);

    /**
     * 查询酒店前三个的信息
     * */
    List<Hotel> selectTwoHotels(HotelExample hotelExample);
    /**
     * 分页查询
     * **/
    List<Hotel> selectByPage(@Param("page") Integer page,@Param("size") Integer size);
    /**
     * 查询总条数
     * **/
    Integer count();
}